# Generated by Django 4.2.4 on 2023-08-20 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('invite_code', models.CharField(max_length=6, verbose_name='Код приглашения')),
                ('code_usage', models.BooleanField(default=False)),
                ('inviter', models.CharField(max_length=6, null=True, verbose_name='Код пригласившего')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('init_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('end_date', models.DateTimeField(null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_app.profile', verbose_name='Пользователь')),
            ],
        ),
    ]
